---
sudo: required
language: python

services:
  - docker

python: "2.7"

virtualenv:
  system_site_packages: false

install:
- pip install --upgrade setuptools
- pip install .

script:
- ansible-galaxy install openmicroscopy.$ROLE --roles-path . --no-deps
# molecule test playbooks expect the directory to match the repository name
- mv openmicroscopy.$ROLE ansible-role-$ROLE
- cd ansible-role-$ROLE
- ../test.sh

### GENERATED ###
env:
- ROLE=basedeps
- ROLE=cadvisor
- ROLE=celery-docker
- ROLE=docker
- ROLE=docker-tools
- ROLE=hosts-populate
- ROLE=ice
- ROLE=java
- ROLE=jekyll-build
- ROLE=local-accounts
- ROLE=logrotate
- ROLE=lvm-partition
- ROLE=munin
- ROLE=mysql-backup
- ROLE=network-cloud-interfaces
- ROLE=nfs-mount
- ROLE=nginx
- ROLE=nginx-proxy
- ROLE=nginx-ssl-selfsigned
- ROLE=omego
- ROLE=omero-logmonitor
- ROLE=omero-python-deps
- ROLE=omero-server
- ROLE=omero-user
- ROLE=omero-web
- ROLE=omero-web-runtime
- ROLE=openstack-volume-storage
- ROLE=postgresql
- ROLE=python-pydata
- ROLE=reboot-server
- ROLE=redis
- ROLE=rsync-server
- ROLE=samba-client
- ROLE=selinux-utils
- ROLE=storage-volume-initialise
- ROLE=sudoers
- ROLE=system-monitor-agent
- ROLE=upgrade-distpackages
- ROLE=versioncontrol-utils
### GENERATED ###
